format="""
$all\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character\
"""

right_format="""$time"""

[time]
disabled = false

[fill]
symbol = " "

[deno]
detect_files = ["mod.ts", "mod.js", "deps.ts", "deps.js", "lock.json"]
detect_extensions = ["ts"]