path = ["/Users/mathspy/.cargo/bin", "/Users/mathspy/.volta/bin", "/usr/local/bin"]
prompt = "starship prompt"
startup = ["alias unwrap = open", "alias open = ^open", "source ~/.cache/starship/init.nu"]
