theme = "rose_pine"

[editor]
color-modes = true
bufferline = "multiple"

[editor.statusline]
center = ["file-type"]
right = [
  "workspace-diagnostics",
  "diagnostics",
  "selections",
  "separator",
  "position",
  "position-percentage",
  "file-encoding",
]

[keys.normal]
"r" = "replace_with_yanked"
"R" = "replace"
"ß" = "split_selection_on_newline"
"…" = "flip_selections"
"d" = "delete_selection_noyank"
"c" = "change_selection_noyank"

[keys.insert]
"j" = {"k" = "normal_mode"}

[keys.select]
"…" = "flip_selections"
