theme = "rose_pine"

[editor]
color-modes = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.statusline]
center = ["file-type"]
right = [
  "workspace-diagnostics",
  "diagnostics",
  "selections",
  "separator",
  "position",
  "position-percentage",
  "file-encoding",
]

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
# Swap replace to from yanked by default
"r" = "replace_with_yanked"
"R" = "replace"

# MacOS alt == option
"ß" = "split_selection_on_newline"
"…" = "flip_selections"
"˜" = "select_next_sibling"
"π" = "select_prev_sibling"
"ˆ" = "shrink_selection"
"ø" = "expand_selection"

# Don't copy on deletion and change
"d" = "delete_selection_noyank"
"c" = "change_selection_noyank"

# Swap paste to paste by default before to match my brain
"p" = "paste_before"
"P" = "paste_after"


[keys.insert]
"j" = {"k" = "normal_mode"}


[keys.select]
# Swap replace to from yanked by default
"r" = "replace_with_yanked"
"R" = "replace"

# MacOS alt == option
"…" = "flip_selections"
