[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "git-commit"
rulers = [50, 72]
text-width = 72

[[language]]
name = "javascript"
formatter = { command = "rome" , args = ["format", "--stdin-file-path", "example.js"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "rome" , args = ["format", "--stdin-file-path", "example.ts"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "rome" , args = ["format", "--stdin-file-path", "example.tsx"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "deno", args = ["fmt", "--ext", "md", "-"] }
auto-format = true

[[language]]
name = "wgsl"
auto-format = true

[[language]]
name = "rust"
text-width = 100
